name = "site-admin"
main = "cloudflare-worker-secure.js"
compatibility_date = "2024-04-14"

routes = [
  { pattern = "ryadom-svami.ru/api/*", zone_name = "ryadom-svami.ru" },
  { pattern = "ryadom-svami.ru/admin*", zone_name = "ryadom-svami.ru" }
]

[[kv_namespaces]]
binding = "SITE_CONTENT"
id = "d849335151244b78992254c3ea149749"

[observability]
enabled = true
